name: Check Format

on:
  pull_request:
    branches: [ $default-branch ]
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

env:
  RUSTUP_MAX_RETRIES: 10
  CARGO_TERM_COLOR: always

jobs:
  format:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Check
        run: cargo fmt --check

